# Generated by Django 5.0.4 on 2024-04-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name_plural': 'sociallinks'},
        ),
    ]
